Repository graphprotocol/indexer-rs, pull requests merged in 2023-08, with the labels that each got.

#13 Add apache-2 license headers
  .github/workflows/license_headers_check.yml
  native/src/attestation.rs
  native/src/lib.rs
  native/src/signature_verification.rs
  service/src/common/address.rs
  service/src/common/database.rs
  service/src/common/indexer_error.rs
  service/src/common/mod.rs
  service/src/common/query_fee_models.rs
  service/src/common/schema.rs
  service/src/common/verifier.rs
  service/src/config.rs
  service/src/graph_node.rs
  service/src/main.rs
  service/src/metrics/mod.rs
  service/src/model/mod.rs
  service/src/query_fee/allocations.rs
  service/src/query_fee/mod.rs
  service/src/query_processor.rs
  service/src/server/mod.rs
  service/src/server/routes/basic.rs
  service/src/server/routes/deployment.rs
  service/src/server/routes/mod.rs
  service/src/server/routes/network.rs
  service/src/server/routes/status.rs
  service/src/server/routes/subgraphs.rs
  service/src/util.rs
Labels: chore

#21 fix: subgraph queries responses
  service/src/graph_node.rs
  service/src/query_processor.rs
  service/src/server/routes/network.rs
  service/src/server/routes/subgraphs.rs
Labels: bug

#23 fix: add 'Bearer ' prefix to supplied free query auth token
  README.md
  service/src/server/mod.rs
Labels: bug

#24 feat: Paid query flow (partial impl)
  Cargo.lock
  native/src/attestation.rs
  service/Cargo.toml
  service/src/graph_node.rs
  service/src/query_processor.rs
  service/src/server/routes/subgraphs.rs
Labels: enhancement

#27 feat: network_query w/ gql and vars
  service/src/graph_node.rs
  service/src/query_processor.rs
Labels: enhancement

#28 refactor: move graph-node instance to main
  service/src/graph_node.rs
  service/src/main.rs
  service/src/query_processor.rs
Labels: refactor

#33 feat: slow and network ratelimiter
  Cargo.lock
  service/Cargo.toml
  service/src/main.rs
  service/src/server/routes/mod.rs
Labels: enhancement

#34 chore: move SubgraphDeploymentID tests to types.rs
  service/src/common/types.rs
  service/src/query_processor.rs
Labels: chore

#35 feat: AllocationMonitor
  Cargo.lock
  service/Cargo.toml
  service/src/allocation_monitor.rs
  service/src/common/allocation.rs
  service/src/common/mod.rs
  service/src/common/types.rs
  service/src/config.rs
  service/src/main.rs
Labels: enhancement

#37 refactor: splits network subgraphs query to NetworkSubgraph
  service/src/allocation_monitor.rs
  service/src/common/mod.rs
  service/src/common/network_subgraph.rs
  service/src/graph_node.rs
  service/src/main.rs
  service/src/query_processor.rs
  service/src/server/mod.rs
  service/src/server/routes/network.rs
Labels: enhancement

#38 feat: attestation signers added to allocation monitor
  Cargo.lock
  service/Cargo.toml
  service/src/allocation_monitor.rs
  service/src/common/allocation.rs
  service/src/common/types.rs
  service/src/main.rs
  service/src/query_processor.rs
  service/src/util.rs
Labels: enhancement

#39 Feat: record query metrics
  service/src/metrics/mod.rs
  service/src/server/routes/subgraphs.rs
Labels: enhancement

#42 refactor: splitting off `AttestationSigners`
  Cargo.lock
  service/Cargo.toml
  service/src/allocation_monitor.rs
  service/src/attestation_signers.rs
  service/src/main.rs
  service/src/query_processor.rs
  service/src/test_vectors.rs
Labels: refactor
