Repository graphprotocol/indexer-rs, pull requests merged in 2023-10, with the labels that each got.

#62 fix: remove name label from QUERY_DURATION metrics
  service/src/metrics/mod.rs
Labels: size:small, p0, type:bug, meta:triaged

#66 Reduce cost model test code
  service/src/common/indexer_management/mod.rs
Labels: size:small, p3, type:refactor

#67 Type network subgraph deployment strongly
  common/src/allocations/monitor.rs
  common/src/network_subgraph/mod.rs
  common/src/test_vectors.rs
  service/src/main.rs
Labels: size:small, p2, type:refactor

#71 feat: add dispute manager eventual
  common/src/attestations/dispute_manager.rs
  common/src/attestations/mod.rs
  common/src/attestations/signers.rs
  common/src/lib.rs
  service/src/main.rs
Labels: size:small, p1, type:refactor

#72 Generalize NetworkSubgraph into SubgraphClient
  common/src/allocations/monitor.rs
  common/src/attestations/dispute_manager.rs
  common/src/lib.rs
  common/src/subgraph_client.rs
  service/src/main.rs
  service/src/server/mod.rs
Labels: size:medium, p1, type:refactor

#78 fix(service): ms intervals treated as seconds
  service/src/main.rs
Labels: size:small, p0, type:bug
