Repository graphprotocol/indexer-rs, pull requests merged in 2023-09, with the labels that each got.

#47 feat: TAP receipts handling + Escrow monitor
  .sqlx/query-17c73722e03764f1bd30f11d6918c0e4df41a5504a3acc779d82fcdf7fdd4e79.json
  Cargo.lock
  migrations/20230912220523_tap_receipts.down.sql
  migrations/20230912220523_tap_receipts.up.sql
  service/Cargo.toml
  service/src/allocation_monitor.rs
  service/src/attestation_signers.rs
  service/src/common/allocation.rs
  service/src/config.rs
  service/src/escrow_monitor.rs
  service/src/main.rs
  service/src/query_processor.rs
  service/src/tap_manager.rs
  service/src/test_vectors.rs
  service/src/util.rs
Labels: size:large, p1, type:feature

#48 ci: enabling SQLX/PG tests
  .github/workflows/tests.yml
  service/src/common/indexer_management_client/resolver.rs
Labels: size:small, p3

#56 chore: remove unused dependencies
  Cargo.lock
  common/Cargo.toml
  service/Cargo.toml
Labels: size:small, p3

#55 feat: limit functions exposed in indexing status API
  Cargo.lock
  common/Cargo.toml
  common/src/graphql.rs
  common/src/lib.rs
  service/Cargo.toml
  service/src/query_processor.rs
  service/src/server/routes/status.rs
Labels: size:medium, p3, type:feature

#58 fix(#57): malformed indexing status response
  service/src/server/routes/status.rs
Labels: size:small, p0, type:bug
