Repository graphprotocol/indexer-rs, pull requests merged in 2024-02, with the labels that each got.

#114 fix(common): subgraph monitor query
  common/src/subgraph_client/monitor.rs
Labels: size:small, p1, type:bug

#116 fix: TAP addresses formatting in DB
  common/src/tap_manager.rs
  tap-agent/src/tap/mod.rs
  tap-agent/src/tap/rav_storage_adapter.rs
  tap-agent/src/tap/receipt_storage_adapter.rs
  tap-agent/src/tap/sender_allocation_relationship.rs
  tap-agent/src/tap/test_utils.rs
Labels: size:small, p0, type:bug

#117 fix(tap-agent): EIP712 domain separator name
  tap-agent/src/agent.rs
Labels: size:small, p0, type:bug

#118 build(deps): fix toolshed deps
  Cargo.lock
  common/Cargo.toml
  common/src/allocations/mod.rs
  common/src/allocations/monitor.rs
  common/src/attestations/dispute_manager.rs
  common/src/attestations/signer.rs
  common/src/attestations/signers.rs
  common/src/escrow_accounts.rs
  common/src/indexer_service/http/config.rs
  common/src/indexer_service/http/indexer_service.rs
  common/src/indexer_service/http/scalar_receipt_header.rs
  common/src/signature_verification.rs
  common/src/tap_manager.rs
  common/src/test_vectors.rs
  service/Cargo.toml
  service/src/database.rs
  tap-agent/Cargo.toml
  tap-agent/src/aggregator_endpoints.rs
  tap-agent/src/config.rs
  tap-agent/src/tap/escrow_adapter.rs
  tap-agent/src/tap/mod.rs
  tap-agent/src/tap/rav_storage_adapter.rs
  tap-agent/src/tap/receipt_checks_adapter.rs
  tap-agent/src/tap/receipt_storage_adapter.rs
  tap-agent/src/tap/sender_allocation_relationship.rs
  tap-agent/src/tap/sender_allocation_relationships_manager.rs
  tap-agent/src/tap/test_utils.rs
Labels: size:medium, p1

#119 chore: set indexer-service version to 1.0.0-alpha.0
  Cargo.lock
  service/Cargo.toml
Labels: size:small, p0

#120 feat(common): add a route /info for operator public key
  common/src/address.rs
  common/src/indexer_service/http/indexer_service.rs
  common/src/lib.rs
Labels: size:small, type:feature

#121 operator info endpoint to return an object
  common/src/indexer_service/http/indexer_service.rs
Labels: size:small, p2, type:bug

#123 fix(tap-agent): make RAV table sequelize-friendly
  .sqlx/query-18da5b2a07db32e58fcbb73ee1537e87b5113dffb5899fce07e5b144f5d5314c.json
  .sqlx/query-7ff23083cf2afaf2c6b9693736053136baee1406f48f61db2b7bc504825a6fc3.json
  .sqlx/query-a25a742980e7995a16f7bb6bb6de1fe8c4569cc8ee35d8594af8ee0c4bd06287.json
  Cargo.lock
  common/src/subgraph_client/monitor.rs
  migrations/20230915230734_tap_ravs.up.sql
  service/src/database.rs
  tap-agent/Cargo.toml
  tap-agent/src/tap/rav_storage_adapter.rs
Labels: size:small, p1

#126 fix: capitalize scalar receipt header
  common/src/indexer_service/http/scalar_receipt_header.rs
Labels: size:small, p1, type:bug
